### ISSUE TITLE
[问题]在【命令行初始化过程】中，报错【2023-05-18 11:12:28.425 ERROR start wdgNodeServer meet err = error listening on [::1]:9991: listen tcp6 [::1]:9991: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. {"component": "@fireboom/node"}】

### ISSUE THREAD

**Issue by hanshou101** [fireboomio/product-manual#10]
# 环境
- Win10
- GitBash终端内运行
- 使用【命令行脚本】进行初始化

# 问题描述
1、当我使用【命令行脚本】，`curl -fsSL https://www.fireboom.io/install.sh | bash -s project-name -t fb-init-todo`或者`./freeboom dev`时，会报错：
```
2023-05-18 11:12:28.425 ERROR start wdgNodeServer meet err = error listening on [::1]:9991: listen tcp6 [::1]:9991: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. {"component": "@fireboom/node"}
```
2、附图：（此为手动执行 ./freeboom dev）
![image](https://github.com/fireboomio/product-manual/assets/19248935/04179dce-1004-409c-9386-a07e7af984ee)

# 已尝试过的方法
- 排查过，相关端口，发现并没有被占用。
- 重启了一遍，然后开机后第一时间，进【Git Bash】启动，还是报这个错。
- 尝试将【Git Bash】以【管理员身份】运行，然后执行【./fireboom  dev】，仍然报这个错。

暂未解决。准备放弃

**Comment by AnsonCode** [comment]
该问题已修复，更新Fireboom后，重试下。
