### ISSUE TITLE
关于上线开关UI优化的一些小建议

### ISSUE THREAD

**Issue by xiyangjun** [fireboomio/product-manual#6]
新建API后的状态默认是非上线的，左上角上线开关不看视频更本不知道那个开关是干啥用的。建议开关加上文字
![image](https://user-images.githubusercontent.com/3805455/233771960-adca7d0f-3441-4058-aa70-12cddc7efa64.png)
在按钮前加上 文字就很直观一眼就可以看到

**Comment by AnsonCode** [comment]
初始设计时，开关有文案，但是也很难理解。索性后来去掉了。后续考虑加个hover提醒。
