### ISSUE TITLE
[问题]在【文档教程——脚本安装】一节中，参照说明进行命令行安装，报错【https://github.com/fireboomio/fireboomio/fb-init-todo.git/  仓库找不到】

### ISSUE THREAD

**Issue by hanshou101** [fireboomio/product-manual#9]
# 问题

1、首先，参照[脚本安装](https://ansons-organization.gitbook.io/product-manual/kuai-su-ru-men/kuai-su-shang-shou#jiao-ben-an-zhuang)这一节，运行 `curl -fsSL https://www.fireboom.io/install.sh | bash -s project-name -t fireboomio/fb-init-todo`。
2、然后，会收到报错提示【https://github.com/fireboomio/fireboomio/fb-init-todo.git/  仓库找不到】。

# 个人解决方案

1、经过细心检查，我手动删除了  多余的【fireboomio】，然后重新执行  `curl -fsSL https://www.fireboom.io/install.sh | bash -s project-name -t fb-init-todo`。这下拉取仓库的这一步，可以正常运行了。
2、经过个人比对，发现官网首页，给出的【命令行示例】是可以正常运行的，和【文档教程——脚本安装】一节的内容有差异。

**Comment by AnsonCode** [comment]
感谢提醒，已更新文档。
